Repository JECT-Study/JECT-Official-WebSite-Client, pull requests merged in 2025-03, with the labels that each got.

#55 refactor: Card 및 Post 컴포넌트 Interaction 주입
  src/components/common/accordion/Accordion.tsx
  src/components/common/card/Card.stories.tsx
  src/components/common/card/Card.tsx
  src/components/common/label/Label.tsx
  src/components/common/post/Post.stories.tsx
  src/components/common/post/Post.tsx
  src/styles/interaction.css
Labels: 👩🏻‍💻frontend, ♻refactor

#63 feat: Role 컴포넌트 구현
  src/assets/images/atom.png
  src/assets/images/clipboard.png
  src/assets/images/cursor.png
  src/assets/images/mobius.png
  src/assets/images/stack.png
  src/components/main/role/RoleBadge.stories.tsx
  src/components/main/role/RoleBadge.tsx
  src/components/main/role/RoleHero.stories.tsx
  src/components/main/role/RoleHero.tsx
  src/types/role.ts
Labels: ✨feature, 👩🏻‍💻frontend

#61 feat: dialog 컴포넌트 구현
  src/components/common/dialog/Dialog.stories.tsx
  src/components/common/dialog/Dialog.tsx
  src/hooks/index.ts
  src/hooks/useDialog.ts
Labels: ✨feature, 👩🏻‍💻frontend

#58 chore: favicon 설정
  index.html
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
Labels: ⚙️chore, 👩🏻‍💻frontend

#74 feat: 아이콘 추가
  src/assets/svg/download.svg
  src/assets/svg/edit.svg
  src/assets/svg/invisible.svg
  src/assets/svg/minus.svg
  src/assets/svg/rightChevron.svg
  src/assets/svg/visible.svg
  src/components/common/icon/Icon.stories.tsx
  src/components/common/icon/Icon.tsx
  src/types/icon.ts
Labels: ⚙️chore, ✨feature

#80 fix: HeroIndex 컴포넌트 수정
  src/components/common/callout/HeroIndex.stories.tsx
  src/components/common/callout/HeroIndex.tsx
Labels: ✨feature, 🐛bug

#77 feat: 활동 페이지 UI 구현
  src/pages/Activity.tsx
  src/router.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#78 feat: 메인페이지 UI 구현
  package-lock.json
  package.json
  src/assets/images/grain.png
  src/components/common/callout/CalloutNumerical.tsx
  src/components/common/callout/Hero.stories.tsx
  src/components/common/callout/Hero.tsx
  src/components/common/callout/HeroIndex.stories.tsx
  src/components/common/callout/HeroIndex.tsx
  src/components/common/tab/Tab.tsx
  src/components/main/animatedSection/AnimatedSection.stories.tsx
  src/components/main/animatedSection/AnimatedSection.tsx
  src/components/main/role/RoleHero.tsx
  src/constants/mainPageData.tsx
  src/main.tsx
  src/pages/Main.tsx
  src/router.tsx
  src/styles/global.css
Labels: ✨feature, 👩🏻‍💻frontend, 😓help wanted

#81 feat: apply-3 페이지 및 지원 완료 페이지 UI 구현
  src/components/common/progress/ProgressIndicator.tsx
  src/constants/applyMessages.tsx
  src/constants/applyPageData.tsx
  src/constants/faqPageData.tsx
  src/constants/path.ts
  src/pages/Apply.tsx
  src/pages/ApplyApplicationInfo.tsx
  src/pages/ApplyComplete.tsx
  src/pages/Faq.tsx
  src/router.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#76 feat: File, Uploader 컴포넌트 구현
  src/components/common/accordion/Accordion.tsx
  src/components/common/file/File.stories.tsx
  src/components/common/file/File.tsx
  src/components/common/input/InputArea.tsx
  src/components/common/input/InputFile.stories.tsx
  src/components/common/input/InputFile.tsx
  src/components/common/input/TextArea.tsx
  src/components/common/uploader/Uploader.stories.tsx
  src/components/common/uploader/Uploader.tsx
  src/constants/file.ts
  src/styles/fileStyle.tsx
  src/types/file.ts
  src/utils/changeFileSizeUnit.ts
  src/utils/validateFileType.ts
Labels: ✨feature

#89 fix: 인터렉션 focus-visible 효과 나타날 때 border가 보이지 않는 버그 해결
  src/components/common/accordion/Accordion.tsx
  src/components/common/button/LabelButton.tsx
  src/styles/interaction.css
Labels: 🐛bug, ♻refactor

#88 bug: 빌드 파일 생성 과정에서 발생한 에러 수정
  src/components/common/button/BlockButton.tsx
  src/components/common/button/LabelButton.stories.tsx
  src/components/common/file/File.stories.tsx
  src/components/common/snackbar/SnackBar.stories.tsx
  src/components/common/tab/Tab.stories.tsx
  src/components/common/tab/Tab.tsx
  src/pages/ApplyApplicationInfo.tsx
Labels: 🐛bug, 👩🏻‍💻frontend

#82 feat: apply-2 페이지 UI 구현
  src/components/apply/NewTabLink.tsx
  src/components/common/input/Input.tsx
  src/components/common/input/InputField.tsx
  src/constants/applyPageData.tsx
  src/pages/Apply.tsx
  src/pages/ApplyApplicationInfo.tsx
  src/pages/ApplyVerify.tsx
  src/pages/ApplyVerifyEmail.tsx
  src/pages/ApplyVerifyPin.tsx
  src/router.tsx
Labels: ✨feature

#85 feat: 지원서 작성 페이지 UI 구현(apply-4)
  src/components/common/input/Input.tsx
  src/components/common/input/InputArea.stories.tsx
  src/components/common/input/InputArea.tsx
  src/components/common/input/InputField.tsx
  src/components/common/input/InputFile.stories.tsx
  src/components/common/input/InputFile.tsx
  src/components/common/input/TextArea.tsx
  src/components/common/uploader/Uploader.tsx
  src/pages/ApplyRegistration.tsx
  src/router.tsx
  src/utils/index.ts
  src/utils/mergeRefs.ts
Labels: ✨feature, 👩🏻‍💻frontend

#102 refactor: requestHandler 제네릭 타입 수정
  src/apis/miniStudy.ts
  src/utils/httpClient.ts
Labels: ♻refactor

#86 feat: CheckBox 컴포넌트 구현
  src/components/common/checkbox/CheckBox.stories.tsx
  src/components/common/checkbox/CheckBox.tsx
  src/components/common/checkbox/CheckBox.types.ts
  src/components/common/checkbox/CheckBoxIcon.tsx
  src/components/common/icon/Icon.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#100 refactor: 스타일 폴더 리팩토링
  src/components/common/button/BlockButton.tsx
  src/components/common/button/LabelButton.tsx
  src/components/common/button/blockButton.style.ts
  src/components/common/button/labelButton.style.ts
  src/components/common/file/File.tsx
  src/components/common/file/file.style.tsx
  src/components/common/icon/Icon.tsx
  src/components/common/icon/icon.style.ts
  src/components/common/label/Label.tsx
  src/components/common/label/label.style.ts
  src/components/common/title/Title.tsx
  src/components/common/title/title.style.ts
Labels: ♻refactor

#104 refactor: 직군명, 이메일 변경 및 데브옵스 애니메이션 비활성화
  src/components/common/select/Select.stories.tsx
  src/components/common/tab/Tab.stories.tsx
  src/components/main/animatedSection/AnimatedSection.tsx
  src/components/main/role/RoleBadge.tsx
  src/components/main/role/RoleHero.stories.tsx
  src/constants/faqPageData.tsx
  src/constants/footer.ts
  src/constants/mainPageData.tsx
Labels: ♻refactor

#99 feat: 젝톡 조회 기능 및 EmptyData 컴포넌트 구현
  src/apis/jectalk.ts
  src/components/common/emptyState/EmptyData.stories.tsx
  src/components/common/emptyState/EmptyData.tsx
  src/constants/apiEndpoint.ts
  src/hooks/useJectalksQuery.ts
  src/hooks/useMiniStudiesQuery.ts
  src/pages/Activity.tsx
  src/types/apis/jectalk.ts
Labels: ✨feature

#111 feat: 젝톡 summary 표시 및 EmptyData 조건부 수정
  src/pages/Activity.tsx
Labels: ✨feature, ♻refactor

#109 feat: 파일 업로드 기능 구현
  package-lock.json
  package.json
  src/apis/jectalk.ts
  src/apis/miniStudy.ts
  src/apis/uploadFileToS3.ts
  src/apis/uploadPortfolio.ts
  src/assets/lottie/ject-loadingSpinner.json
  src/components/apply/FileField.tsx
  src/components/apply/UrlField.tsx
  src/components/apply/textField.tsx
  src/components/common/file/File.stories.tsx
  src/components/common/file/File.tsx
  src/components/common/file/FileItem.stories.tsx
  src/components/common/file/FileItem.tsx
  src/components/common/file/fileItem.style.tsx
  src/components/common/input/InputFile.stories.tsx
  src/components/common/input/InputFile.tsx
  src/components/common/uploader/Uploader.tsx
  src/constants/apiEndpoint.ts
  src/constants/applyMessages.tsx
  src/constants/file.ts
  src/hooks/useCloseOutside.ts
  src/hooks/useCreatePresignedUrlsQuery.ts
  src/hooks/useUploadFileToS3Query.ts
  src/pages/ApplyRegistration.tsx
  src/types/apis/answer.ts
  src/types/apis/jectalk.ts
  src/types/apis/miniStudy.ts
  src/types/apis/uploadFile.ts
  src/types/ui/file.ts
  src/utils/changeFileSizeUnit.ts
  src/utils/extractFileInfo.ts
  src/utils/validateFileMaxSize.ts
  src/utils/validateFileType.ts
  src/utils/validateInvalidFile.ts
Labels: ✨feature

#112 feat: 지원서 플로우 기능 구현
  src/apis/changeJob.ts
  src/apis/draft.ts
  src/apis/question.ts
  src/apis/submitAnswer.ts
  src/components/apply/Answers.tsx
  src/components/apply/FileField.tsx
  src/components/apply/UrlField.tsx
  src/components/apply/selectBox.tsx
  src/components/apply/textField.tsx
  src/components/common/dialog/Dialog.tsx
  src/components/common/file/FileItem.tsx
  src/components/common/input/Input.tsx
  src/components/common/input/InputArea.tsx
  src/constants/apiEndpoint.ts
  src/constants/applyMessages.tsx
  src/hooks/useApplicationState.ts
  src/hooks/useChangeJobQuery.ts
  src/hooks/useDraftQuery.ts
  src/hooks/useQuestionsQuery.ts
  src/hooks/useSaveDraftQuery.ts
  src/hooks/useSubmitAnswerQuery.ts
  src/hooks/useUploadFileToS3Query.ts
  src/pages/ApplyRegistration.tsx
  src/types/apis/answer.ts
  src/types/apis/question.ts
  src/utils/extractFileInfo.ts
  src/utils/validateAnswersPayload.ts
  src/utils/validateUrl.ts
Labels: ✨feature, 👩🏻‍💻frontend, ♻refactor
