Repository JECT-Study/JECT-Official-WebSite-Client, pull requests merged in 2025-02, with the labels that each got.

#5 feat: 디자인 시스템 및 스타일링 셋업
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/assets/fonts/PretendardVariable.woff2
  src/App.tsx
  src/index.css
  src/main.tsx
  src/styles/global.css
  src/styles/tokens/environment.css
  src/styles/tokens/index.ts
  src/styles/tokens/scheme.css
  src/styles/tokens/semantic.css
  src/styles/tokens/semantic.json
  src/styles/tokens/typography.css
  token.config.js
Labels: ⚙️chore, 👩🏻‍💻frontend

#10 chore: 스토리북 환경 구축 및 CI 설정
  .github/workflows/storybook.yml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  eslint.config.js
  package-lock.json
  package.json
  src/components/Button.stories.tsx
  src/components/Button.tsx
  tailwind.config.ts
  tsconfig.app.json
Labels: ⚙️chore

#13 feat: 폴더 구조 세팅 및 절대 경로 처리
  eslint.config.js
  package-lock.json
  package.json
  src/apis/index.ts
  src/assets/index.ts
  src/constants/index.ts
  src/hooks/index.ts
  src/main.tsx
  src/pages/index.ts
  src/stores/index.ts
  src/types/index.ts
  src/utils/index.ts
  tsconfig.app.json
  vite.config.ts
Labels: ⚙️chore, 👩🏻‍💻frontend

#15 chore: Qodana 스크립트 수정
  .github/workflows/qodana.yml
  .github/workflows/qodana_code_quality.yml
Labels: ⚙️chore

#20 feat: Label 및 Badge 컴포넌트 구현
  src/components/common/Badge.stories.tsx
  src/components/common/Badge.tsx
  src/components/common/Label.stories.tsx
  src/components/common/Label.tsx
  src/styles/labelStyle.ts
Labels: ✨feature, 👩🏻‍💻frontend

#22 fix: 인터렉션 컴포넌트 수정 및 storybook 설정
  .storybook/preview.ts
  src/components/common/Badge.stories.tsx
  src/components/common/Badge.tsx
  src/components/common/Interaction.stories.tsx
  src/components/common/Interaction.tsx
  src/components/common/Label.stories.tsx
  src/components/common/Label.tsx
  src/styles/interactionStyle.ts
  src/styles/tokens/typography.css
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#23 feat: Title, Callout, Hero 컴포넌트 구현
  src/components/common/Label.tsx
  src/components/common/Title.stories.tsx
  src/components/common/Title.tsx
  src/components/common/callout/CalloutInformation.stories.tsx
  src/components/common/callout/CalloutInformation.tsx
  src/components/common/callout/CalloutNumerical.stories.tsx
  src/components/common/callout/CalloutNumerical.tsx
  src/components/common/callout/Hero.stories.tsx
  src/components/common/callout/Hero.tsx
  src/components/common/callout/HeroIndex.stories.tsx
  src/components/common/callout/HeroIndex.tsx
  src/styles/labelStyle.ts
  src/styles/titleStyle.ts
  src/styles/tokens/scheme.css
Labels: ✨feature, 👩🏻‍💻frontend

#29 feat: progress 컴포넌트 구현
  src/components/common/Title.tsx
  src/components/common/progress/ProgressBridge.tsx
  src/components/common/progress/ProgressIndex.stories.tsx
  src/components/common/progress/ProgressIndex.tsx
  src/components/common/progress/ProgressIndicator.stories.tsx
  src/components/common/progress/ProgressIndicator.tsx
  src/components/common/progress/ProgressItem.stories.tsx
  src/components/common/progress/ProgressItem.tsx
  src/components/common/progress/ProgressVerticalBridge.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#30 feat: 범용성있는 버튼 컴포넌트 구현
  .storybook/preview.ts
  package-lock.json
  package.json
  src/components/Button.stories.tsx
  src/components/Button.tsx
  src/components/common/Interaction.tsx
  src/components/common/button/BlockButton.stories.tsx
  src/components/common/button/BlockButton.tsx
  src/components/common/button/LabelButton.stories.tsx
  src/components/common/button/LabelButton.tsx
  src/styles/blockButtonStyle.ts
  src/styles/interactionStyle.ts
  src/styles/labelButtonStyle.ts
  src/styles/storyStyles.css
Labels: ✨feature, 👩🏻‍💻frontend

#32 feat: 아이코노그래피를 기반으로 아이콘 컴포넌트 구현
  package-lock.json
  package.json
  src/assets/svg/check.svg
  src/assets/svg/clear.svg
  src/assets/svg/dropDown.svg
  src/assets/svg/error.svg
  src/assets/svg/expand.svg
  src/assets/svg/file.svg
  src/assets/svg/forward.svg
  src/assets/svg/github.svg
  src/assets/svg/less.svg
  src/assets/svg/northEast.svg
  src/assets/svg/question.svg
  src/assets/svg/upload.svg
  src/assets/svg/youtube.svg
  src/components/common/icon/Icon.stories.tsx
  src/components/common/icon/Icon.tsx
  src/styles/iconStyle.ts
  src/types/icon.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: ✨feature, 👩🏻‍💻frontend

#35 fix: 인터랙션 컴포넌트 재구현 및 semantic 컬러 토큰 업데이트
  src/components/common/Interaction.stories.tsx
  src/components/common/Interaction.tsx
  src/components/common/button/BlockButton.tsx
  src/components/common/button/LabelButton.tsx
  src/components/common/interaction/Interaction.stories.tsx
  src/components/common/interaction/Interaction.tsx
  src/styles/global.css
  src/styles/interactionStyle.ts
  src/styles/tokens/semantic.css
  src/styles/tokens/semantic.json
  token.config.js
Labels: ✨feature, 🐛bug

#36 feat: Input 컴포넌트 구현
  src/components/common/Label.tsx
  src/components/common/input/Input.stories.tsx
  src/components/common/input/Input.tsx
  src/components/common/input/InputArea.stories.tsx
  src/components/common/input/InputArea.tsx
  src/components/common/input/InputField.stories.tsx
  src/components/common/input/InputField.tsx
  src/components/common/input/TextArea.tsx
  src/styles/global.css
  src/styles/tokens/environment.css
Labels: ✨feature, 👩🏻‍💻frontend

#40 feat: 지원하기 페이지 UI 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/apply/NewTabLink.tsx
  src/components/common/Title.stories.tsx
  src/components/common/progress/ProgressItem.tsx
  src/constants/applyData.tsx
  src/pages/Apply.tsx
  src/router.tsx
  src/utils/scrollFunction.ts
  tsconfig.app.json
Labels: ✨feature, 👩🏻‍💻frontend

#37 feat: Card와 Post 컴포넌트 구현
  src/assets/CardSample.png
  src/components/common/card/Card.stories.tsx
  src/components/common/card/Card.tsx
  src/components/common/post/Post.stories.tsx
  src/components/common/post/Post.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#39 feat: 탭 컴포넌트 구현
  src/components/common/tab/Tab.stories.tsx
  src/components/common/tab/Tab.tsx
  src/components/common/tab/Tab.types.ts
Labels: ✨feature, 👩🏻‍💻frontend

#53 feat: FAQ 페이지 UI 구현 및 아코디언 컴포넌트 구현
  src/components/common/accordion/Accordion.stories.tsx
  src/components/common/accordion/Accordion.tsx
  src/components/common/badge/Badge.stories.tsx
  src/components/common/badge/Badge.tsx
  src/components/common/callout/CalloutInformation.tsx
  src/components/common/callout/CalloutNumerical.tsx
  src/components/common/callout/Hero.tsx
  src/components/common/callout/HeroIndex.tsx
  src/components/common/card/Card.tsx
  src/components/common/input/InputArea.tsx
  src/components/common/input/InputField.tsx
  src/components/common/label/Label.stories.tsx
  src/components/common/label/Label.tsx
  src/components/common/post/Post.tsx
  src/components/common/progress/ProgressItem.tsx
  src/components/common/title/Title.stories.tsx
  src/components/common/title/Title.tsx
  src/constants/faqData.tsx
  src/pages/Apply.tsx
  src/pages/Faq.tsx
  src/router.tsx
  src/styles/global.css
Labels: ✨feature, 👩🏻‍💻frontend

#44 feat: Select 컴포넌트 구현
  src/components/common/select/Select.stories.tsx
  src/components/common/select/Select.tsx
  src/components/common/tab/Tab.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#45 feat: SnackBar 컴포넌트 구현
  src/components/common/button/BlockButton.stories.tsx
  src/components/common/button/BlockButton.tsx
  src/components/common/button/LabelButton.stories.tsx
  src/components/common/button/LabelButton.tsx
  src/components/common/snackbar/SnackBar.stories.tsx
  src/components/common/snackbar/SnackBar.tsx
  src/styles/blockButtonStyle.ts
  src/styles/labelButtonStyle.ts
Labels: ✨feature, 👩🏻‍💻frontend

#60 Fix: 인터렉션 재구현 3차
  src/components/common/accordion/Accordion.tsx
  src/components/common/button/BlockButton.tsx
  src/components/common/button/LabelButton.tsx
  src/components/common/interaction/Interaction.stories.tsx
  src/components/common/interaction/Interaction.tsx
  src/components/common/select/Select.tsx
  src/components/common/tab/Tab.tsx
  src/styles/blockButtonStyle.ts
  src/styles/global.css
  src/styles/interaction.css
  src/styles/interactionStyle.ts
  src/styles/labelButtonStyle.ts
  src/types/interaction.ts
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend
