Repository JECT-Study/JECT-Official-WebSite-Client, pull requests merged in 2025-04, with the labels that each got.

#120 feat: 페이지 하단 지원 스낵바 구현
  src/components/apply/ApplySnackBar.tsx
  src/components/common/snackbar/SnackBar.tsx
  src/constants/applyMessages.tsx
  src/pages/Activity.tsx
  src/pages/Faq.tsx
  src/pages/Main.tsx
  src/pages/Project.tsx
  src/pages/ProjectDetail.tsx
  src/pages/index.ts
Labels: ✨feature

#122 feat: 로컬스토리지 자동 임시 저장 기능 구현
  src/components/common/file/FileItem.tsx
  src/pages/ApplyRegistration.tsx
  src/utils/draftUtils.ts
Labels: ✨feature, 🐛bug

#114 feat: 회원 비회원 인증 및 회원정보 등록 기능
  package-lock.json
  package.json
  src/apis/apply.ts
  src/apis/auth.ts
  src/components/common/accordion/Accordion.tsx
  src/components/common/checkbox/CheckBox.stories.tsx
  src/components/common/checkbox/CheckBox.tsx
  src/components/common/input/Input.tsx
  src/components/common/label/Label.tsx
  src/constants/apiEndpoint.ts
  src/constants/faqPageData.tsx
  src/hooks/useApplyApplicantInfoForm.ts
  src/hooks/useApplyAuthCodeForm.ts
  src/hooks/useApplyEmailForm.ts
  src/hooks/useApplyPinForm.ts
  src/hooks/useCheckEmailExistMutation.ts
  src/hooks/useEmailAuthCodeMutation.ts
  src/hooks/useMemberProfileInitialMutation.ts
  src/hooks/usePinLoginMutation.ts
  src/hooks/useRegisterMemberMutation.ts
  src/hooks/useVerificationEmailCodeMutation.ts
  src/pages/ApplyApplicationInfo.tsx
  src/pages/ApplyVerify.tsx
  src/pages/ApplyVerifyEmail.tsx
  src/pages/ApplyVerifyPin.tsx
  src/schema/applySchema.ts
  src/styles/global.css
  src/types/apis/apply.ts
  src/types/apis/auth.ts
  src/types/apis/response.ts
  src/utils/formHelpers.ts
  src/utils/httpClient.ts
  src/utils/interceptor.ts
  tsconfig.app.json
  vite-env.d.ts
Labels: ✨feature, 👩🏻‍💻frontend

#133 bug: workflow runner 버전 업데이트
  .github/workflows/storybook.yml
Labels: ⚙️chore, 🐛bug

#127 refactor: 다이얼로그 함수 호출식으로 재구현
  src/components/common/dialog/Dialog.stories.tsx
  src/components/common/dialog/Dialog.tsx
  src/components/layout/Layout.tsx
  src/constants/dialog.tsx
  src/hooks/useApplicationState.ts
  src/hooks/useDialog.ts
  src/pages/ApplyRegistration.tsx
  src/stores/dialogStore.ts
  src/types/ui/dialog.ts
Labels: ♻refactor

#135 chore: 배포 스크립트 및 환경 설정
  .github/workflows/deploy.yml
Labels: ⚙️chore

#138 fix: Uploader 스토리북 에러 해결
  src/components/common/uploader/Uploader.stories.tsx
Labels: 🐛bug

#130 feat: 답변 SELECT 필드 추가
  src/components/apply/Answers.tsx
  src/components/apply/FileField.tsx
  src/components/apply/SelectField.tsx
  src/components/apply/UrlField.tsx
  src/components/apply/selectBox.tsx
  src/components/apply/textField.tsx
  src/hooks/useCloseOutside.ts
  src/types/apis/question.ts
  src/utils/validateAnswersPayload.ts
Labels: ✨feature

#134 feat: 임시저장 불러오기 다이얼로그 표시 및 임시지원서 제거 api 연동 (+지원서 관련 함수 및 타입 리팩토링)
  src/apis/application.ts
  src/apis/changeJob.ts
  src/apis/draft.ts
  src/apis/question.ts
  src/apis/submitAnswer.ts
  src/apis/uploadFileToS3.ts
  src/apis/uploadPortfolio.ts
  src/components/apply/Answers.tsx
  src/components/apply/ApplySnackBar.tsx
  src/components/apply/FileField.tsx
  src/components/apply/SelectField.tsx
  src/components/apply/UrlField.tsx
  src/components/apply/selectBox.tsx
  src/components/apply/textField.tsx
  src/components/common/file/FileItem.tsx
  src/constants/apiEndpoint.ts
  src/constants/index.ts
  src/hooks/useApplicationState.ts
  src/hooks/useChangeJobQuery.ts
  src/hooks/useCreatePresignedUrlsMutation.ts
  src/hooks/useCreatePresignedUrlsQuery.ts
  src/hooks/useDeleteDraftMutation.ts
  src/hooks/useDraftQuery.ts
  src/hooks/useMiniStudiesQuery.ts
  src/hooks/useQuestionsQuery.ts
  src/hooks/useSaveDraftMutation.ts
  src/hooks/useSaveDraftQuery.ts
  src/hooks/useSubmitAnswerMutation.ts
  src/hooks/useSubmitAnswerQuery.ts
  src/hooks/useUploadFileToS3Mutation.ts
  src/hooks/useUploadFileToS3Query.ts
  src/pages/ApplyRegistration.tsx
  src/pages/ApplyVerifyPin.tsx
  src/types/apis/answer.ts
  src/types/apis/application.ts
  src/types/apis/question.ts
  src/types/apis/uploadFile.ts
  src/types/ui/application.ts
  src/utils/draftUtils.ts
  src/utils/extractFileInfo.ts
  src/utils/validateApplication.ts
Labels: ✨feature, ♻refactor

#144 feat: FAQ 페이지 기능 변경 및 개선
  src/components/common/accordion/Accordion.stories.tsx
  src/components/common/accordion/Accordion.tsx
  src/constants/faqPageData.tsx
  src/hooks/useFaqNavigation.ts
  src/pages/ApplyVerifyEmail.tsx
  src/pages/Faq.tsx
  src/router.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#146 feat: PIN 재설정 기능 구현
  src/apis/apply.ts
  src/constants/apiEndpoint.ts
  src/hooks/useResetPinMutation.ts
  src/pages/ApplyVerifyEmail.tsx
  src/pages/ApplyVerifyPin.tsx
  src/types/apis/apply.ts
Labels: ✨feature, 👩🏻‍💻frontend

#143 feat: 에러 핸들링
  src/App.tsx
  src/assets/images/question.png
  src/assets/svg/refresh.svg
  src/components/apply/Answers.tsx
  src/components/apply/RedirectIfSubmitted.tsx
  src/components/common/icon/Icon.tsx
  src/components/layout/PagesContainer.tsx
  src/constants/dialog.tsx
  src/constants/path.ts
  src/errors/APIError.ts
  src/errors/errorMappings.ts
  src/hooks/useDraftQuery.ts
  src/hooks/useGlobalErrorHandler.ts
  src/hooks/useQuestionsQuery.ts
  src/hooks/useUploadFileToS3Mutation.ts
  src/pages/ApplyRegistration.tsx
  src/pages/ApplyVerifyPin.tsx
  src/pages/NonSpecificError.tsx
  src/pages/NotFoundError.tsx
  src/router.tsx
  src/stores/dialogStore.ts
  src/types/ui/dialog.ts
  src/types/ui/icon.ts
  src/utils/httpClient.ts
Labels: ✨feature

#153 bug: 임시 회원가입 시 토큰 핸들링이 정상적으로 처리되지 않는 문제 해결
  src/apis/apply.ts
  src/hooks/useRegisterMemberMutation.ts
  src/pages/ApplyVerifyEmail.tsx
  src/types/apis/apply.ts
Labels: 🐛bug

#145 chore: sentry 에러 모니터링 도구 도입
  .gitignore
  package-lock.json
  package.json
  src/components/apply/Answers.tsx
  src/components/common/accordion/Accordion.stories.tsx
  src/hooks/useDraftQuery.ts
  src/hooks/useGlobalErrorHandler.ts
  src/instrument.ts
  src/main.tsx
  src/pages/ApplyVerifyPin.tsx
  src/pages/NonSpecificError.tsx
  src/router.tsx
  vite-env.d.ts
  vite.config.ts
Labels: ⚙️chore

#154 fix: 배포 전 발견된 수정 및 추가 사항 작업
  src/App.tsx
  src/assets/images/cone.png
  src/components/common/navigation/Navigation.tsx
  src/components/layout/PagesContainer.tsx
  src/constants/applyPageData.tsx
  src/constants/mainPageData.tsx
  src/constants/path.ts
  src/pages/ApplyVerifyEmail.tsx
  src/pages/Maintenance.tsx
  src/router.tsx
Labels: ✨feature

#157 bug: 임시 회원가입 버튼 클릭 이벤트가 전송안되는 버그 해결
  src/pages/ApplyVerifyEmail.tsx
Labels: 🐛bug

#161 fix: 스크롤 최상단 이동 기능 추가, 지원서 임시 저장 조회 및 파일 업로드 버그 수정
  src/components/apply/Answers.tsx
  src/components/apply/FileField.tsx
  src/components/layout/Layout.tsx
  src/components/layout/ScrollToTop.tsx
  src/constants/applyMessages.tsx
  src/constants/applyPageData.tsx
  src/hooks/useDraftQuery.ts
  src/pages/ApplyVerifyEmail.tsx
  src/pages/ApplyVerifyPin.tsx
Labels: 🐛bug

#166 fix: 지원 페이지 전반적인 내용과 UI 수정
  src/constants/applyPageData.tsx
  src/pages/Apply.tsx
Labels: 🐛bug

#164 bug: Faq 페이지 내 탭 이동 시 히스토리가 유지되는 문제 해결
  src/hooks/useFaqNavigation.ts
Labels: 🐛bug

#168 chore: QA 용 환경 구축 시 배포 설정
  vercel.json
Labels: ⚙️chore

#171 fix: 지원서 작성 페이지 벗어날 경우 다이얼로그 표시
  src/constants/dialog.tsx
  src/hooks/useDirtyCheckDialog.ts
  src/pages/ApplyRegistration.tsx
  src/types/ui/dialog.ts
Labels: ✨feature, 🐛bug

#173 bug: 지원 플로우 중 인증 과정 중에 발견한 이슈 해결
  src/pages/ApplyVerify.tsx
  src/pages/ApplyVerifyEmail.tsx
  src/pages/ApplyVerifyPin.tsx
Labels: 🐛bug

#178 fix: 지원서 문항 조회 토스트, 지원서 제출자 검증 로직 추가 등 이슈 해결
  src/apis/application.ts
  src/components/apply/Answers.tsx
  src/constants/apiEndpoint.ts
  src/constants/applyPageData.tsx
  src/hooks/useCheckApplicationStatus.ts
  src/pages/ApplyVerifyPin.tsx
Labels: 🐛bug

#181 bug: 토큰 재발급 후 기존 api 호출이 수행되지 않는 문제 해결
  src/apis/auth.ts
Labels: 🐛bug

#183 fix: 지원자 정보 작성 페이지에서 지원서 제출 여부 판단
  package-lock.json
  package.json
  src/errors/APIError.ts
  src/hooks/useCheckApplicationStatus.ts
  src/hooks/useCreatePresignedUrlsMutation.ts
  src/hooks/useDeleteDraftMutation.ts
  src/hooks/useGlobalErrorHandler.ts
  src/hooks/useGoBackCheckDialog.ts
  src/hooks/useJectalksQuery.ts
  src/hooks/useMiniStudiesQuery.ts
  src/hooks/useSaveDraftMutation.ts
  src/hooks/useSubmitAnswerMutation.ts
  src/hooks/useUploadFileToS3Mutation.ts
  src/pages/ApplyApplicationInfo.tsx
  src/pages/ApplyRegistration.tsx
  src/pages/ApplyVerifyPin.tsx
  src/utils/cryto.ts
  src/utils/draftUtils.ts
  src/utils/httpClient.ts
  vite-env.d.ts
Labels: ✨feature, 🐛bug

#184 feat: 불필요한 로그를 제거하고 모니터링 로그로 대체
  src/apis/apply.ts
  src/constants/apiEndpoint.ts
  src/hooks/useCheckEmailExistMutation.ts
  src/hooks/useEmailAuthCodeMutation.ts
  src/hooks/useMemberProfileInitialMutation.ts
  src/hooks/useMemberProfileInitialStatusQuery.ts
  src/hooks/usePinLoginMutation.ts
  src/hooks/useRegisterMemberMutation.ts
  src/hooks/useResetPinMutation.ts
  src/hooks/useVerificationEmailCodeMutation.ts
  src/instrument.ts
  src/pages/ApplyApplicationInfo.tsx
  src/pages/ApplyVerifyEmail.tsx
  src/pages/ApplyVerifyPin.tsx
  src/types/apis/apply.ts
  src/utils/errorLogger.ts
Labels: ✨feature, 🐛bug

#189 Bug: 임시 회원 최초 프로필 등록 여부 확인 api 연결
  src/hooks/useMemberProfileInitialStatusQuery.ts
  src/pages/ApplyVerifyPin.tsx
  src/types/apis/apply.ts
Labels: ✨feature, 🐛bug

#194 chore: Amplitude 기본 설정
  index.html
Labels: ⚙️chore

#192 feat: 매일 오전 5시~7시 점검 페이지 전환 기능 구현
  src/App.tsx
  src/components/common/footer/MobileFooter.tsx
  src/hooks/useRedirectMaintenance.ts
  src/pages/Maintenance.tsx
  src/pages/TempMobile.tsx
Labels: ✨feature
